language: elixir
elixir:
  - 1.8
otp_release:
  - 21.0
matrix:
  exclude:
    - elixir: 1.5
      otp_release: 21.0
    - elixir: 1.4
      otp_release: 21.0
    - elixir: 1.7
      otp_release: 19.3
    - elixir: 1.7
      otp_release: 20.3
    - elixir: 1.8
      otp_release: 19.3
    - elixir: 1.8
      otp_release: 20.3
sudo: false
env:
  global:
    - ELIXIR_ASSERT_TIMEOUT=2000
  matrix:
    - COWBOY_VERSION=2.0
before_script:
  - mix deps.get
  - nvm install 6.2 && nvm use 6.2
script:
  - mix test
  - cd ../assets && npm install && npm test
after_script:
  - cd $TRAVIS_BUILD_DIR
  - MIX_ENV=docs mix inch.report
cache:
  directories:
  - assets/node_modules
